spring:
  application:
    name: fastdfs
  thymeleaf: #html页面
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 9527



fdfs:
  so-timeout: 2500       # 读取时间
  connect-timeout: 600   # 连接超时时间
  thumb-image:           # 缩略图
    width: 100
    height: 100
  tracker-list:          # tracker服务配置地址列表
    #- 10.5.28.144:23000
    - 10.5.28.142:22122

upload:
  #base-url: http://10.5.28.144:22122/
  base-url: http://10.5.28.148:31564/static/  #图片上传后,可访问的根目录
  allow-types:    #图片类型
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif